<a href="https://colab.research.google.com/github/GuddKumar143/CodeMaster/blob/main/Numpy143.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,6])
print(x)
print(type(x))
print("iD Array:", x)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
iD Array: [1 2 3 4 5 6]


In [ ]:
y = [2,4,6,8,10]
print(y)
print(type(y))

[2, 4, 6, 8, 10]
<class 'list'>


In [ ]:
#2D Array(Matrix)
B = ( [12,24,36,48], [10,20,30,40,50])
print("2D Array:", B)
print(type(B))

2D Array: ([12, 24, 36, 48], [10, 20, 30, 40, 50])
<class 'tuple'>


In [ ]:
%timeit [j**4 for j in range(1,9)]

771 ns ± 11.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
import numpy as np
%timeit np.arange(1,9)**4

1.87 µs ± 523 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
import numpy as np
R = [2,4,6,8,10]
d = np.array([2,4,6,8,10,12,14,16])
print(d)
print(type(d))
print(d.ndim)

[ 2  4  6  8 10 12 14 16]
<class 'numpy.ndarray'>
1


In [ ]:
l = []
for i in range(1,5):
  int_l = int(input("Enter : "))
  l.append(int_l)

  print(np.array(l))




In [ ]:
grid = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("total:",grid.sum())
print("per row:", grid.sum(axis = 1))
print("double stickers:\n", grid*2)


total: 45
per row: [ 6 15 24]
double stickers:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
# 2-D array
ar2 = np.array([[1,2,3,4,5], [5,4,3,2,1]])
print(ar2)
print("Here, ndim Number:", ar2.ndim)

[[1 2 3 4 5]
 [5 4 3 2 1]]
Here, Ndim Number: 2


In [ ]:
# 3-D Array
ar3 = np.array([[[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]]])
print(ar3)
print("ndim Number:", ar3.ndim )

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
ndim Number: 3


In [ ]:
arn = np.array([1,3,2,3,4,3,2], ndmin = 10)
print(arn)
print("Here ndim number:", arn.ndim)

[[[[[[[[[[1 3 2 3 4 3 2]]]]]]]]]]
Here ndim number: 10


In [ ]:
#ZERO
import numpy as np
ar_zero = np.zeros(4)

ar_zero1 = np.zeros(( 3,4))

print(ar_zero)

print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ones
ar_one = np.ones(4)
print(ar_one)



[1. 1. 1. 1.]


In [ ]:
#Empty
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [ ]:
# arrange
ar_arange = np.arange(10)
print(ar_arange)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Daigonal
ar_Daigonal = np.eye(4)
print(ar_Daigonal)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:

ar_Daigonal = np.eye(4,5)
print(ar_Daigonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
#linespace
ar_linesp = np.linspace(0,20, num = 5)
print(ar_linesp)


[ 0.  5. 10. 15. 20.]


In [ ]:
# Random / rand() function
var_r = np.random.rand(5)
print(var_r)


[0.47980642 0.14515784 0.13362378 0.33979125 0.18704927]


In [ ]:
#randn()
var_r1 = np.random.randn(5)
print(var_r1)

[ 1.58838205 -1.87682365  0.58559612  0.42922364  1.40303193]


In [ ]:
#ranf()
var_r2 = np.random.ranf(5)
print(var_r2)

[0.65447887 0.19161667 0.61549059 0.43448811 0.6416621 ]


In [ ]:
#randint()
var_r3 = np.random.randint(5, 20, 5)
print(var_r3)

[18 17 18  6 10]


In [ ]:
# integer Data Types
import numpy as np
var_d = np.array([1,2,3,4,5])
print("Data Type:", var_d.dtype)

Data Type: int64


In [ ]:
# float Data types
var_d = np.array([1.2,2.3,3.4,4.5,5.6])
print("Data Type:", var_d.dtype)

Data Type: float64


In [ ]:
# string Data Types
var_d = np.array(["a","b","c","d"])
print("Data Type:", var_d.dtype)

Data Type: <U1


In [ ]:
# string data Type + integer Data Type
var_d = np.array(["a","b","c","d",1,2,3,4])
print("Data Type:", var_d.dtype)

Data Type: <U21


In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4], dtype = np.int8)
print("Data Type : ", x.dtype)
print(x)


Data Type :  int8


In [ ]:
x1 = np.array([1, 2, 3, 4], dtype ="f")
print("Data Type : ", x.dtype)
print(x1)

Data Type :  int8
[1. 2. 3. 4.]


In [ ]:
x2 = np.array([1, 2, 3, 4])
new = np.float32(x2)

print("Data Type : ", x.dtype)
print("Data Type : ", new.dtype)
print(x2)
print(new)

Data Type :  int8
Data Type :  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
x3 = np.array([1, 2, 3, 4])
new = np.float32(x3)

new_one = np.int_(new)

print("Data Type : ", x3.dtype)
print("Data Type : ", new.dtype)
print("Data Typen : ", new_one.dtype)
print(x2)
print(new)
print(new_one)

Data Type :  int64
Data Type :  float32
Data Typen :  int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
x4 = np.array([1,2,3,4])

new_1 = x4.astype(float)
new_2 = x4.astype(str)
new_3 = x4.astype(bool)

print(x4)
print(new_1)
print(new_2)
print(new_3)

[1 2 3 4]
[1. 2. 3. 4.]
['1' '2' '3' '4']
[ True  True  True  True]


In [ ]:
# SHAPE
import numpy as np
var = np.array([[1,2,3,4,5], [1,2, 3, 4,5]])
print(var)
print()
print(var.shape)


[[1 2 3 4 5]
 [1 2 3 4 5]]

(2, 5)


In [ ]:
var1 = np.array([1, 2, 3, 4, 5], ndmin = 4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)


[[[[1 2 3 4 5]]]]
4

(1, 1, 1, 5)


In [ ]:
# 2D Dimension
var2 = np.array([1,2, 3, 4, 5,6, 1, 2, 3, ])
print(var2)
print(var2.ndim)

print()

x = var2.reshape(3,3)
print(x)
print(x.ndim)


[1 2 3 4 5 6 1 2 3]
1

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2


In [ ]:
# 3D Dimension
var3 = np.array([1,2, 3, 4, 5, 6, 7, 8, 9, 10 ,11, 12])
print(var3)
print(var3.ndim)

print()

x1 = var3.reshape(2,3,2)
print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
#Arithmeetic Operation
import numpy as np
var = np.array([1,2,3,4])

varadd = var + 3
print(varadd)

[4 5 6 7]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd1 = var1 + var2

print(varadd1)

[2 4 6 8]


In [ ]:
#Arithmeetic Operation
import numpy as np
var = np.array([1,2,3,4])

varadd = var - 3
print(varadd)

[-2 -1  0  1]


In [ ]:
#Arithmeetic Operation
import numpy as np
var = np.array([1,2,3,4])

varadd = var * 3
print(varadd)

[ 3  6  9 12]


In [ ]:
#Arithmeetic Operation
import numpy as np
var = np.array([1,2,3,4])

varadd = var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [ ]:
#Arithmeetic Operation
import numpy as np
var = np.array([1,2,3,4])

varadd = var % 3
print(varadd)

[1 2 0 1]


In [ ]:
# 2D Array
var1 = np.array([[1,2,3, 4],[1,2,3,4]])
var2 = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])

varrad = np.add(var1, var2)
print(varrad)


[[ 6  8 10 12]
 [10 12 14 16]]


In [ ]:
var1 = np.array([[1,2,3, 4],[1,2,3,4]])
var2 = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])

print(var1)
print()
print(var2)
print()

varrad = np.add(var1, var2)
print(varrad)

[[1 2 3 4]
 [1 2 3 4]]

[[ 5  6  7  8]
 [ 9 10 11 12]]

[[ 6  8 10 12]
 [10 12 14 16]]


In [ ]:
import numpy as np
var0 = np.array([1,2,3,4])

varadd = np.reciprocal(var0)

print(varadd)

[1 0 0 0]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6])

print("min : ", np.min(var), np.argmin(var))
print("max : ", np.max(var),np.argmax(var))
print("sqrt : ", np.sqrt(var))


min :  1 0
max :  6 5
sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [ ]:
var4 = np.array([[2, 1, 3], [9, 5, 6]])
print(np.min(var4, axis=1))
print(np.min(var4, axis=0))

[1 5]
[2 1 3]


In [ ]:
# sin and cos ....values
import numpy as np

var2 = np.array([1, 2, 3])
var3 = np.array([30, 45, 60, 90])

print(np.sin(var2))
print(np.cos(var2))
print(np.tan(var2))
print(np.cumsum(var2))

print(np.sin(var3))
print(np.cos(var3))
print(np.tan(var3))
print(np.cumsum(var3))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[1 3 6]
[-0.98803162  0.85090352 -0.30481062  0.89399666]
[ 0.15425145  0.52532199 -0.95241298 -0.44807362]
[-6.4053312   1.61977519  0.32004039 -1.99520041]
[ 30  75 135 225]


In [ ]:
# broadcaast in numpy
import numpy as np
var1 = np.array([1, 2, 3])
print(var1.shape)
print()
print(var1)
print()

var2 = np.array([[1], [2], [3]])
print(var2.shape)
print()
print(var2)
print()

print(var1 + var2)



(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
# Broadcat in numpy
x = np.array([[1], [2]])
print(x.shape)

y = np.array([[1,2,3], [1,2,3]])
print(y.shape)

print(x * y)

(2, 1)
(2, 3)
[[1 2 3]
 [2 4 6]]


In [ ]:
# inddexing in numpy
import numpy as np
var1 = np.array([1, 2, 3, 4, 5, 6])

print(var1[0])
print(var1[-4])

1
3


In [ ]:
# indexing in numpy
var2 = np.array([[2, 3, 4, 5, 6], [ 7, 8, 9, 10, 11]])

print(var2)
print(var2.ndim)
print()
print(var2[0, 2])

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
2

4


In [ ]:
# indexing in numpy
# 3D Array
var3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

print(var3)
print(var3.ndim)
print()
print(var3[0, 1, 1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

5


In [ ]:
# sclicing in numpy
import numpy as np
var = np.array([1,2,3,4,5,6,7])
#   0,1,2,3,4,5,6

print(var)
print()
print("2 to 5 : ", var[1:5])
print(" 2 to End :", var[1:])
print("start to as :", var[:5])
print("stop : ", var[::2])
print("stop : ", var[1:6:2])



[1 2 3 4 5 6 7]

2 to 5 :  [2 3 4 5]
 2 to End : [2 3 4 5 6 7]
start to as : [1 2 3 4 5]
stop :  [1 3 5 7]
stop :  [2 4 6]


In [ ]:
var1 = np.array([[[1,2,3,4,5], [9,8,7,6,5],[11, 12, 13, 14,15]]])
print(var1)
print()

print(" 8 to 5 : ", var1[0, 1, 1:])

[[[ 1  2  3  4  5]
  [ 9  8  7  6  5]
  [11 12 13 14 15]]]

 8 to 5 :  [8 7 6 5]


In [ ]:
#iteration
var = np.array([9, 8, 7, 6, 5,4])
print(var)
print()
for i in var:
  print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [ ]:
var1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
print(var1)
print()
for j in var1:
  print(j)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]


In [ ]:
var1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
print(var1)
print()

for j in var1:
  print(j)

for k in var1:
  for element in k:
    print(element)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]
1
2
3
4
1
2
3
4


In [ ]:
var3 = np.array([[[1, 2,3,4], [1, 2, 3, 4]]])
print(var3)
print(var3.ndim)
print()

for i in var3:
  for j in i:
    for k in j:
      print(k)

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [ ]:
var3 = np.array([[[1, 2,3,4], [1, 2, 3, 4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3, flags = ['buffered'], op_dtypes = [("S")]):
  print(i)

[[[1 2 3 4]
  [1 2 3 4]]]
3

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [ ]:
var3 = np.array([[[9, 8, 7, 6], [1, 2, 3, 4]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
  print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


In [ ]:
# copy vs view
import numpy as np
var = np.array([1,2,3,4])
co = var.copy()
vi = var.view()

print("var : ",var)
print(" copy : ",co)
print(" view :", vi)


var :  [1 2 3 4]
 copy :  [1 2 3 4]
 view : [1 2 3 4]


In [ ]:
# join Array
import numpy as np
var1 = np.array([1, 2, 3, 4])
var2 = np.array([9, 8, 7, 6])

ar = np.concatenate((var1, var2))
print(ar)

[1 2 3 4 9 8 7 6]


In [ ]:
var = np.array([[1, 2], [3, 4]])
var1 = np.array([[9, 8], [7, 6]])
print(var)

[[1 2]
 [3 4]]


In [ ]:
var = np.array([[1, 2], [3, 4]])
var1 = np.array([[9, 8], [7, 6]])

ar_new = np.concatenate((var, var1), axis = 0)
print(var)
print()
print(var1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [ ]:
var_1 = np.array([1, 2, 3, 4])
var_2 = np.array([9, 8, 7, 6])

a_new = np.stack((var_1, var_2), axis = 1)
a_new1 = np.hstack((var_1, var_2)) # row
a_new2 = np.vstack((var_1, var_2))  # column
a_new3 = np.dstack((var_1, var_2))  # height
a_new4 = np.stack((var_1, var_2), axis = 0)   #  Axis Zero

print(a_new)
print()
print(" Row : ", a_new1)
print()
print(" column : ", a_new2)
print()
print(" Height: ", a_new3)
print()
print(" Axis Zero : ", a_new4)


[[1 9]
 [2 8]
 [3 7]
 [4 6]]

 Row :  [1 2 3 4 9 8 7 6]

 column :  [[1 2 3 4]
 [9 8 7 6]]

 Height:  [[[1 9]
  [2 8]
  [3 7]
  [4 6]]]

 Axis Zero :  [[1 2 3 4]
 [9 8 7 6]]


In [ ]:
# Split Array
import numpy as np
var = np.array([1, 2, 3, 4, 5, 6])
print(var)
print()

sp = np.array_split(var, 3)
print(sp)
print()
print(sp[0])
print(sp[1])
print(sp[2])


[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]

[1 2]
[3 4]
[5 6]


In [ ]:
var4 = np.array([[1, 2], [3, 4],[5, 6]])
print(var4)
print()
ar4 = np.array_split(var4, 3)
ar5 = np.array_split(var4, 3, axis = 1)

print(ar4)
print()
print(ar5)


[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


In [ ]:
# search, in numpy
import numpy as np

var5 = np.array([1, 2, 3, 4, 2, 6, 7, 2 , 3, 5, 9 ,1 , 5, 6 ,4])

x = np.where(var5 == 2)
x1 = np.where((var5 %2) == 0)
print(x)
print()
print(x1)


(array([1, 4, 7]),)

(array([ 1,  3,  4,  5,  7, 13, 14]),)


In [ ]:
var6 = np.array([1, 2, 3, 4, 2, 6, 7, 2 , 3, 5, 9 ,1 , 5, 6 ,4])


x6 = np.searchsorted(var6,  [5,6,7] , side = "right")
print(x6)

[13 15 15]


In [ ]:
#sort Array
var_6 = np.array([[4, 2, 3], [1, 12, 5], [22, 52,6]])
print(np.sort(var_6))



[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [ ]:
var_7 = np.array(["h", "G", "u","D","a","b","p","Z","d"])
print(np.sort(var_7))

['D' 'G' 'Z' 'a' 'b' 'd' 'h' 'p' 'u']


In [ ]:
#Filter Array
var_8 = np.array(["a", "s","d","f"])
f = [True, False, True, False]

new_a = var_8[f]
print(new_a)
print(type(new_a))

['a' 'd']
<class 'numpy.ndarray'>


In [ ]:
# shuffle
import numpy as np
var_9 = np.array([1, 2, 3, 4, 5])
np.random.shuffle(var_9)
print(var_9)

[5 4 2 1 3]


In [ ]:
# Unique function
var_10 = np.array([1,2, 3,4, 2,5, 2, 6, 2, 7])
x = np.unique(var_10,return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]), array([1, 4, 1, 1, 1, 1, 1]))


In [ ]:
# Resize function
var_11 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.resize(var_11, (3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#Flatten function
var_11 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.resize(var_11, (3,2))
print(y)
print()
print("Flatten : ", y.flatten(order = "F"))
print("Ravel :",np.ravel(y, order ="F"))
print("Ravel ,, order of A:",np.ravel(y, order ="A"))


[[1 2]
 [3 4]
 [5 6]]

Flatten :  [1 3 5 2 4 6]
Ravel : [1 3 5 2 4 6]
Ravel ,, order of A: [1 2 3 4 5 6]


In [ ]:
# inserst function
import numpy as np
var = np.array([1, 2, 3, 4,5])
print(var)
print()
v = np.insert(var, 2, 30)
print(v)
print()
v2 = np.insert(var, (2,4), 6.5)
print(v2)


[1 2 3 4 5]

[ 1  2 30  3  4  5]

[1 2 6 3 4 6 5]


In [ ]:
var3 = np.array([[1,2,3],[1,2,3]])
v3 = np.insert(var3, 2, 6, axis = 0)
print(v3)
print()
v4 = np.insert(var3, 2, 6, axis = 1)
print(v4)

[[1 2 3]
 [1 2 3]
 [6 6 6]]

[[1 2 6 3]
 [1 2 6 3]]


In [ ]:
var1 = np.array([[1,2,3],[1,2,3]])
v1 =np.append(var1, [[45, 44, 23]],axis = 0)
print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [45 44 23]]


In [ ]:
#Delete function
import numpy as np
var2 = np.array([1, 2, 3, 4,5])
print(var2)
print()
d = np.delete(var2, 2)
print(d)
print()



[1 2 3 4 5]

[1 2 4 5]



In [ ]:
# Matrix in Numpy Arrays
import numpy as np
var = np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))


[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [ ]:
# Arithmetic Operation
import numpy as np
var = np.array([[1,2,3],[1,2,3]])
var1 = np.array([[10,20,30], [40,50,60]])
print(var)
print(type(var))
print()
print(var1)
print(type(var1))
print()
print("Addition : ", var + var1)
print()
print("Subtraction : ", var - var1)
print()
print("Element-wise Multiplication :", var * var1) # Element-wise multiplication with arrays
print()
print("Division (element-wise) : ", var / var1)
print()

# Standard matrix multiplication - This will cause a ValueError with these shapes
# print("Standard Matrix Multiplication : ", var @ var1)
# print("Standard Matrix Multiplication (using dot) : ", np.dot(var, var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>

Addition :  [[11 22 33]
 [41 52 63]]

Subtraction :  [[ -9 -18 -27]
 [-39 -48 -57]]

Element-wise Multiplication : [[ 10  40  90]
 [ 40 100 180]]

Division (element-wise) :  [[0.1   0.1   0.1  ]
 [0.025 0.04  0.05 ]]



In [ ]:
var1= np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [ ]:
# Matrix Functions :- Transpose
import numpy as np
var1 = np.matrix([[1,2,3],[1,2,3]])
print(var1)
print()
print(np.transpose(var1))
print()
print(var1.T)
print()
print(np.swapaxes(var1, 0,1))

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]


In [ ]:
var2 = np.array([[1,2,3],[1,2,3]])
print(var2)
print()
print(np.swapaxes(var2, 0,1))

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]


In [ ]:
# inverse in matrix
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.inv(var3))


[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.matrix_power(var4, 2))
print()
print(np.linalg.matrix_power(var4, 0))
print()
print(np.linalg.matrix_power(var4, -2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [ ]:
# determinant
var5 = np.matrix([[1,2,3],[3,4,5],[6,7,8]])
print(var5)
print()
print(np.linalg.det(var5))
print()

[[1 2 3]
 [3 4 5]
 [6 7 8]]

0.0

